import { getUserAndProfile } from "@/lib/auth";
import { signOut } from "@/app/login/actions";
import { MainHeader } from "@/components/main-header";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Privacy Policy — GenZ",
  description: "How GenZ collects, uses, and protects your data.",
};

const SECTIONS = [
  {
    title: "1. What We Collect",
    body: `We collect information you provide directly — name, email, phone number, and (for manufacturers) GST and business details submitted during verification. We also collect information generated by using the platform: order history, product interactions, uploaded content, and basic device/usage data such as browser type and pages visited.`,
  },
  {
    title: "2. How We Use Your Information",
    body: `We use collected data to operate your account, process and route orders between buyers and manufacturers, verify manufacturer credentials, send transactional and (with consent) marketing communications, and improve platform features. We do not sell your personal data to third parties.`,
  },
  {
    title: "3. Sharing With Manufacturers & Buyers",
    body: `To fulfill an order, we share the necessary contact and shipping details between the buyer and the manufacturer involved in that transaction. Manufacturers only receive what's needed to complete the order — we don't expose your full account data to sellers you haven't transacted with.`,
  },
  {
    title: "4. Third-Party Services",
    body: `We rely on trusted infrastructure providers — including our database and authentication provider (Supabase), image hosting, and analytics tools — to run the platform. These providers process data on our behalf under their own security and confidentiality commitments and do not use your data for their own purposes.`,
  },
  {
    title: "5. Cookies",
    body: `GenZ uses essential cookies to keep you signed in and remember basic preferences. Where non-essential cookies (such as analytics) are used, you'll see a cookie consent notice with the option to accept or decline.`,
  },
  {
    title: "6. Data Retention",
    body: `We retain account and transaction data for as long as your account is active and for a reasonable period after, to meet legal, accounting, or dispute-resolution obligations. You can request deletion of your account data at any time, subject to records we're legally required to keep.`,
  },
  {
    title: "7. Your Rights",
    body: `You can access, correct, or request deletion of your personal data by contacting us. Manufacturer verification records (GST filings, business documents) may be retained longer where required for compliance and fraud-prevention purposes.`,
  },
  {
    title: "8. Data Security",
    body: `We use industry-standard measures — encrypted connections, hashed credentials, and access-controlled infrastructure — to protect your data. No system is completely immune to risk, and we encourage using a strong, unique password for your GenZ account.`,
  },
  {
    title: "9. Children's Privacy",
    body: `GenZ is not directed at children under 18. We do not knowingly collect personal information from children. If you believe a child has provided us data, contact us and we'll remove it.`,
  },
  {
    title: "10. Changes to This Policy",
    body: `We may update this Privacy Policy periodically to reflect changes in our practices or applicable law. Material changes will be communicated via the platform or registered email before they take effect.`,
  },
  {
    title: "11. Contact",
    body: `For privacy-related questions or data requests, reach us at genz.official.hq@gmail.com or via our Contact page.`,
  },
];

export default async function PrivacyPage() {
  const session = await getUserAndProfile();
  const isLoggedIn = !!session;
  const role = session?.profile?.role;

  return (
    <div className="bg-background flex min-h-screen flex-col font-sans text-foreground antialiased">
      <MainHeader
        isLoggedIn={isLoggedIn}
        role={role}
        userName={session?.profile?.full_name || session?.email}
        signOutAction={signOut}
      />

      <main className="flex-1">
        <section className="py-20 sm:py-24 px-6 sm:px-12 border-b border-black/10">
          <div className="mx-auto max-w-3xl text-left">
            <span className="eyebrow text-charcoal mb-3 block">Legal</span>
            <h1 className="font-serif text-4xl sm:text-6xl font-normal leading-[1.05] tracking-tight text-deep-forest mb-4">
              Privacy Policy
            </h1>
            <p className="text-charcoal text-sm">Last updated: July 2026</p>
          </div>
        </section>

        <section className="py-16 sm:py-20 px-6 sm:px-12">
          <div className="mx-auto max-w-3xl bg-paper-white rounded-2xl border border-black/10 p-8 sm:p-12 flex flex-col gap-10">
            {SECTIONS.map((s) => (
              <div key={s.title}>
                <h2 className="font-serif text-xl sm:text-2xl font-normal text-deep-forest mb-3 tracking-tight">
                  {s.title}
                </h2>
                <p className="text-charcoal text-sm sm:text-base leading-relaxed">{s.body}</p>
              </div>
            ))}
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
